

name: Update addon latest version

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        slug:
          description: 'AddOn slug (e.g., bayrol-poolaccess-mqtt-dev)'
          required: true
        version:
          description: 'Target version (e.g., 1.0.0)'
          required: true

jobs:
  
  update_version:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo SLUG ${{ github.event.inputs.slug }}
          echo VERSION ${{ github.event.inputs.version }}
