

name: Update addon latest version

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        slug:
          description: 'Addon slug (e.g., bayrol-poolaccess-mqtt-dev)'
          required: true
        version:
          description: 'Addon target version (e.g., 1.0.0-dev)'
          required: true

jobs:
  
  update_version:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          jq --version || apt-get install -y jq

      - name: Update Version
        env:
          CONFIG_PATH: "./${{ github.event.inputs.slug }}/config.json"
        run: |
          echo SLUG ${{ github.event.inputs.slug }}
          echo VERSION ${{ github.event.inputs.version }}
          echo CONFIG_PATH $CONFIG_PATH
          
          echo Current version $(jq '.version' $CONFIG_PATH)
          echo "$(jq '.version = "'${{ github.event.inputs.version }}'"' $CONFIG_PATH)" > $CONFIG_PATH
          echo Updated version  $(jq '.version' $CONFIG_PATH)

       # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
